# Generated by Django 4.2.6 on 2023-11-12 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('category_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField(default=0)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.categorymodel')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.usermodel')),
            ],
        ),
    ]
